// NavBar
export const ArrayList = [
  "All",
  "Sell",
  "Best seller",
  "Today deal's",
  "Mobiles",
  "Customer Service",
  "Electronic",
  "Home & Kitchen",
  "Fashion",
  "Books",
  "Top deal",
  "ALl",
  "Best seller",
  "Mobiles",
  "Books",
];
//NavItem
export const ArrayDot = [
  {
    Image: "./Images/s1.jpg",
    head: "Upgrade your home amazone Brands ",
    text: "Clothing",
    image: "./Images/s2.jpg",
    text2: "Footwear",
    image1: "./Images/s3.jpg",
    text1: "Watches",
    image3: "./Images/s4.jpg",
    text3: "bags & luggage",
    share: "Explore All",
  },
  {
    Image: "./Images/c1.jpg",
    head: "Car & bike essentials | Up to 60% off",
    text: "Cleaning ",
    image: "./Images/c2.jpg",
    text2: "tyre & rim care",
    image1: "./Images/c3.jpg",
    text1: "Helments",
    image3: "./Images/c4.jpg",
    text3: "Vaccum Cleaner",
    share: "Explore All",
  },
  {
    Image: "./Images/f1.jpg",
    head: "Revamp your home in style",
    text: "Bedsheet ",
    image: "./Images/f2.jpg",
    text2: "Home ",
    image1: "./Images/f3.jpg",
    text1: "Home Storage",
    image3: "./Images/f4.jpg",
    text3: "Lighting ",
    share: "Explore All",
  },
  {
    Image: "./Images/m1.jpg",
    head: "Shop & Pay | Earn rewards daily",
    text: "claim your scratch card",
    image: "./Images/m2.jpg",
    text2: "Reddem your collection",
    image1: "./Images/m3.jpg",
    text1: "Unlock more ",
    image3: "./Images/m4.jpg",
    text3: "Explore all offer",
    share: "Explore All",
  },
];

// Offers
export const Feature = [
  {
    id: 1,
    BeautyImageTwo: "./Images/BeautySmallOne.jpg",
    BeautyImageOne: "./Images/BeautySmall.jpg",
    BeautyImage: "./Images/BeautyTen.jpg",
    Images: "./Images/BeautyNine.jpg",
    Image: "./Images/BeautyOne.jpg",
    Deal: "DEAL OF THE DAY:",
    price: "	₹767.00 (₹1,535 /100)",
    MRP: "M.R.P.:	₹650.00",
    Taxes: "Inclusive of all taxes",
    yousave: "You Save:",
    save: "₹83.00 (10%)",
    text: "Pilgrim 25% AHA + 2% BHA + 5% PHA Peeling Solution for Face | 10-Minute Facial | Chemical peel ",
    Delivery: "FREE Delivery over ₹499. Fulfilled by Amazon.",
    About: "About This Item",
    ItemTwo:
      "✅CHEMICAL PEEL CLEARS SKIN - Glycolic Acid exfoliates the top layer of dead skin cells to reveal fresh, radiant skin underneath. It reduces unwanted discolourations of the skin and offers a firm, even skin tone & texture.",
    Item: "✅CHEMICAL EXFOLIATOR FOR FACE - Salicylic Acid is known for its pore-exfoliating abilities. It regulates sebum production and eliminates stubborn blackheads and whiteheads. Deep cleans pores, fades spots and smooths for even, baby-soft skin",
    Free: "FREE delivery Sunday, 13 November on first order. ",
    Location: "Select you Location",
    sold: "Sold by Pilgrim India and Fulfilled by Amazon.",
    ItemThree:
      "✅AHA BHA PEELING SOLUTION EXFOLIATES DEAD SKIN CELLS - Lactic Acid brightens and refines skin texture. Reduces acne and alleviates dullness. Treat yourself to the luxury of an at-home facial with the Pilgrim 25% AHA, 2% BHA, 5% PHA Peeling Solution.",
    ItemFour:
      "✅NATURAL INGREDIENTS, NO TOXINS - Crafted following strict guidelines of THE PILGRIM CODE, the Peeling Solution is FDA approved, Contains No Paraben, No Sulphates, No Mineral Oils as well as other harsh chemicals and is cruelty-free.",
    ItemFive:
      "✅Increases skin hydration to reduce the look of fine lines & wrinkles. Gently exfoliates to reveal bright and youthful skin.",
    DetailKey: "Product Dimensions :",
    DetailValue: "19 x 11 x 9.5 cm; 30 Grams",
    DetailKeyOne: "Date First Available:",
    DetailValueOne: "27 December 2019",
    DetailKeyTwo: "Manufacturer :",
    DetailValueTwo: "For Pilgrim India (Aelius Parallel Holdings Pvt Ltd.)",
    DetailKeyThree: "ASIN  : ",
    DetailValueThree: "B0836Y7S2C",
    DetailKeyFour: "Item model number  : ",
    DetailValueFour: "PGKNS1",
    DetailKeyFive: "Country of Origin  : ",
    DetailValueFive: " India",
    DetailKeySix: "Manufacturer  : ",
    DetailValueSix: "For Pilgrim India (Aelius Parallel Holdings Pvt Ltd.)",
    DetailKeySeven: "Item Weight  : ",
    DetailValueSeven: "90 g",
    DetailKeyEight: "Net Quantity  :",
    DetailValueEight: "30 millilitre",
    DetailKeyNine: "Best Sellers Rank: ",
    DetailValueNine: "#1,618 in Beauty",
    Detail: "Product Detail",
    save_extra: "Save Extra",
    save_extraTwo: "with 2 offers",
    Partner_Offer: "Partner Offers (2):",
    Partner_Offer_Two:
      "Buy more and save up to 10% extra. Offered by Pilgrim India",
    Bank_Offer: "Bank Offer (2): ",
    Bank_Offer_Two:
      "10% Instant Discount up to INR 500 on OneCard Credit Card Trxn. Min purchase value INR 2500 ",
    Important: "Important information",
    Safety: "Safety Information",
    SafetyHead:
      "Use twice a day, morning & night. Apply under a high SPF sunscreen during the day.",
    Indication: "Indications:",
    IndicationHead:
      "Apply 3-5 drops of serum to clean and dry skin before creams, oils or moisturizers. Spread evenly across the face and neck with your fingertips. Gently pat it on for enhanced absorption.",
  },
  {
    id: 2,
    MRP: "M.R.P.:	₹650.00",
    Taxes: "Inclusive of all taxes",
    yousave: "You Save:",
    Delivery: "FREE Delivery over ₹499. Fulfilled by Amazon.",
    About: "About This Item",
    ItemTwo:
      "REDUCES ACNE MARKS : The Tea Tree & 10% Niacinamide Blemish Remover Serum with 1% Zinc PCA is a potent formulation to diminish blemishes and acne marks. Say hello to blemish-free crystal clear skin!",
    Item: "10% NIACINAMIDE : 10% Niacinamide helps repair the skin barrier and brighten. Combined with 1% Zinc PCA, this lightweight serum helps refin",
    Image: "./Images/BeautyTwo.jpg",
    Deal: "DEAL OF THE DAY",
    price: "₹225.00 (₹225.00/100g)",
    save: "₹25.00 (10%)",
    Delivery: "FREE Delivery over ₹499. Fulfilled by Amazon.",
    Price: "₹491.00 (₹1,636.67 /100 ml)",
    Free: "FREE delivery Sunday, 13 November on first order. ",
    Location: "Select you Location",
    sold: "Sold by Pilgrim India and Fulfilled by Amazon.",
    Deal: "DEAL OF THE DAY:",
    text: "Organix Mantra Tea Tree Essential Oils for Skin, Hair, Face, Acne Care, 100% Pure, Natural and Undiluted Therapeutic Grade Essential Oil (Tea Tree 15ML) ",
    ItemThree:
      "AHA BHA PEELING SOLUTION EXFOLIATES DEAD SKIN CELLS - Lactic Acid brightens and refines skin texture. Reduces acne and alleviates dullness. Treat yourself to the luxury of an at-home facial with the Pilgrim 25% AHA, 2% BHA, 5% PHA Peeling Solution.",
    ItemFour:
      "NATURAL INGREDIENTS, NO TOXINS - Crafted following strict guidelines of THE PILGRIM CODE, the Peeling Solution is FDA approved, Contains No Paraben, No Sulphates, No Mineral Oils as well as other harsh chemicals and is cruelty-free.",
    ItemFive:
      "Increases skin hydration to reduce the look of fine lines & wrinkles. Gently exfoliates to reveal bright and youthful skin.",
    DetailKey: "Product Dimensions :",
    DetailValue: "19 x 11 x 9.5 cm; 30 Grams",
    DetailKeyOne: "Date First Available:",
    DetailValueOne: "27 December 2019",
    DetailKeyTwo: "Manufacturer :",
    DetailValueTwo: "For Pilgrim India (Aelius Parallel Holdings Pvt Ltd.)",
    DetailKeyThree: "ASIN  : ",
    DetailValueThree: "B0836Y7S2C",
    DetailKeyFour: "Item model number  : ",
    DetailValueFour: "PGKNS1",
    DetailKeyFive: "Country of Origin  : ",
    DetailValueFive: " India",
    DetailKeySix: "Manufacturer  : ",
    DetailValueSix: "For Pilgrim India (Aelius Parallel Holdings Pvt Ltd.)",
    DetailKeySeven: "Item Weight  : ",
    DetailValueSeven: "90 g",
    DetailKeyEight: "Net Quantity  :",
    DetailValueEight: "30 millilitre",
    DetailKeyNine: "Best Sellers Rank: ",
    DetailValueNine: "#1,618 in Beauty",
    Detail: "Product Detail",
    save_extra: "Save Extra",
    save_extraTwo: "with 2 offers",
    Partner_Offer: "Partner Offers (2):",
    Partner_Offer_Two:
      "Buy more and save up to 10% extra. Offered by Pilgrim India",
    Bank_Offer: "Bank Offer (2): ",
    Bank_Offer_Two:
      "10% Instant Discount up to INR 500 on OneCard Credit Card Trxn. Min purchase value INR 2500 ",
    Important: "Important information",
    Safety: "Safety Information",
    SafetyHead:
      "Use twice a day, morning & night. Apply under a high SPF sunscreen during the day.",
    Indication: "Indications:",
    IndicationHead:
      "Apply 3-5 drops of serum to clean and dry skin before creams, oils or moisturizers. Spread evenly across the face and neck with your fingertips. Gently pat it on for enhanced absorption.",
  },
  {
    id: 3,
    MRP: "M.R.P.:	₹650.00",
    Taxes: "Inclusive of all taxes",
    yousave: "You Save:",
    Delivery: "FREE Delivery over ₹499. Fulfilled by Amazon.",
    About: "About This Item",
    ItemTwo:
      "CHEMICAL PEEL CLEARS SKIN - Glycolic Acid exfoliates the top layer of dead skin cells to reveal fresh, radiant skin underneath. It reduces unwanted discolourations of the skin and offers a firm, even skin tone & texture.",
    Item: "CHEMICAL EXFOLIATOR FOR FACE - Salicylic Acid is known for its pore-exfoliating abilities. It regulates sebum production and eliminates stubborn blackheads and whiteheads. Deep cleans pores, fades spots and smooths for even, baby-soft skin",
    Image: "./Images/BeautyThree.jpg",
    Deal: "DEAL OF THE DAY",
    price: "New Price:	₹999.00 Price:	₹795.00",
    save: "₹204.00 (20%)",
    text: "Vantro Foam Cannon for Pressure Washer - Original Wide Neck, Wide Base Heavy Duty Foam Gun for Detailing ",
    Delivery: "FREE Delivery over ₹499. Fulfilled by Amazon.",
    Price: "₹491.00 (₹1,636.67 /100 ml)",
    Free: "FREE delivery Sunday, 13 November on first order. ",
    Location: "Select you Location",
    sold: "Sold by Pilgrim India and Fulfilled by Amazon.",
    Deal: "DEAL OF THE DAY:",
    ItemThree:
      "AHA BHA PEELING SOLUTION EXFOLIATES DEAD SKIN CELLS - Lactic Acid brightens and refines skin texture. Reduces acne and alleviates dullness. Treat yourself to the luxury of an at-home facial with the Pilgrim 25% AHA, 2% BHA, 5% PHA Peeling Solution.",
    ItemFour:
      "NATURAL INGREDIENTS, NO TOXINS - Crafted following strict guidelines of THE PILGRIM CODE, the Peeling Solution is FDA approved, Contains No Paraben, No Sulphates, No Mineral Oils as well as other harsh chemicals and is cruelty-free.",
    ItemFive:
      "Increases skin hydration to reduce the look of fine lines & wrinkles. Gently exfoliates to reveal bright and youthful skin.",
    DetailKey: "Product Dimensions :",
    DetailValue: "19 x 11 x 9.5 cm; 30 Grams",
    DetailKeyOne: "Date First Available:",
    DetailValueOne: "27 December 2019",
    DetailKeyTwo: "Manufacturer :",
    DetailValueTwo: "For Pilgrim India (Aelius Parallel Holdings Pvt Ltd.)",
    DetailKeyThree: "ASIN  : ",
    DetailValueThree: "B0836Y7S2C",
    DetailKeyFour: "Item model number  : ",
    DetailValueFour: "PGKNS1",
    DetailKeyFive: "Country of Origin  : ",
    DetailValueFive: " India",
    DetailKeySix: "Manufacturer  : ",
    DetailValueSix: "For Pilgrim India (Aelius Parallel Holdings Pvt Ltd.)",
    DetailKeySeven: "Item Weight  : ",
    DetailValueSeven: "90 g",
    DetailKeyEight: "Net Quantity  :",
    DetailValueEight: "30 millilitre",
    DetailKeyNine: "Best Sellers Rank: ",
    DetailValueNine: "#1,618 in Beauty",
    Detail: "Product Detail",
    save_extra: "Save Extra",
    save_extraTwo: "with 2 offers",
    Partner_Offer: "Partner Offers (2):",
    Partner_Offer_Two:
      "Buy more and save up to 10% extra. Offered by Pilgrim India",
    Bank_Offer: "Bank Offer (2): ",
    Bank_Offer_Two:
      "10% Instant Discount up to INR 500 on OneCard Credit Card Trxn. Min purchase value INR 2500 ",
    Important: "Important information",
    Safety: "Safety Information",
    SafetyHead:
      "Use twice a day, morning & night. Apply under a high SPF sunscreen during the day.",
    Indication: "Indications:",
    IndicationHead:
      "Apply 3-5 drops of serum to clean and dry skin before creams, oils or moisturizers. Spread evenly across the face and neck with your fingertips. Gently pat it on for enhanced absorption.",
  },
  {
    id: 4,
    MRP: "M.R.P.:	₹650.00",
    Taxes: "Inclusive of all taxes",
    yousave: "You Save:",
    Delivery: "FREE Delivery over ₹499. Fulfilled by Amazon.",
    About: "About This Item",
    ItemTwo:
      "As extra virgin olive oil is pure and free from any refining chemical",
    Item: "Extra virgin olive oil is made from the process of applying some pressure to the olive seeds. we can safely use that for our skin.",
    save: "₹851.00 (53%)",
    Image: "./Images/BeautyFour.webp",
    Deal: "DEAL OF THE DAY",
    price: "	₹749.00 (₹749.00 / l)",
    Delivery: "FREE Delivery over ₹499. Fulfilled by Amazon.",
    Price: "₹491.00 (₹1,636.67 /100 ml)",
    Free: "FREE delivery Sunday, 13 November on first order. ",
    Location: "Select you Location",
    sold: "Sold by Pilgrim India and Fulfilled by Amazon.",
    Deal: "DEAL OF THE DAY:",
    text: "Figaro Extra Virgin Olive Oil- 100% Natural and Cold Extracted- Perfect for Salad, Paratha, Marinade- Imported from Spain- 5L Jar ",
    ItemThree:
      "AHA BHA PEELING SOLUTION EXFOLIATES DEAD SKIN CELLS - Lactic Acid brightens and refines skin texture. Reduces acne and alleviates dullness. Treat yourself to the luxury of an at-home facial with the Pilgrim 25% AHA, 2% BHA, 5% PHA Peeling Solution.",
    ItemFour:
      "NATURAL INGREDIENTS, NO TOXINS - Crafted following strict guidelines of THE PILGRIM CODE, the Peeling Solution is FDA approved, Contains No Paraben, No Sulphates, No Mineral Oils as well as other harsh chemicals and is cruelty-free.",
    ItemFive:
      "Increases skin hydration to reduce the look of fine lines & wrinkles. Gently exfoliates to reveal bright and youthful skin.",
    DetailKey: "Product Dimensions :",
    DetailValue: "19 x 11 x 9.5 cm; 30 Grams",
    DetailKeyOne: "Date First Available:",
    DetailValueOne: "27 December 2019",
    DetailKeyTwo: "Manufacturer :",
    DetailValueTwo: "For Pilgrim India (Aelius Parallel Holdings Pvt Ltd.)",
    DetailKeyThree: "ASIN  : ",
    DetailValueThree: "B0836Y7S2C",
    DetailKeyFour: "Item model number  : ",
    DetailValueFour: "PGKNS1",
    DetailKeyFive: "Country of Origin  : ",
    DetailValueFive: " India",
    DetailKeySix: "Manufacturer  : ",
    DetailValueSix: "For Pilgrim India (Aelius Parallel Holdings Pvt Ltd.)",
    DetailKeySeven: "Item Weight  : ",
    DetailValueSeven: "90 g",
    DetailKeyEight: "Net Quantity  :",
    DetailValueEight: "30 millilitre",
    DetailKeyNine: "Best Sellers Rank: ",
    DetailValueNine: "#1,618 in Beauty",
    Detail: "Product Detail",
    save_extra: "Save Extra",
    save_extraTwo: "with 2 offers",
    Partner_Offer: "Partner Offers (2):",
    Partner_Offer_Two:
      "Buy more and save up to 10% extra. Offered by Pilgrim India",
    Bank_Offer: "Bank Offer (2): ",
    Bank_Offer_Two:
      "10% Instant Discount up to INR 500 on OneCard Credit Card Trxn. Min purchase value INR 2500 ",
    Important: "Important information",
    Safety: "Safety Information",
    SafetyHead:
      "Use twice a day, morning & night. Apply under a high SPF sunscreen during the day.",
    Indication: "Indications:",
    IndicationHead:
      "Apply 3-5 drops of serum to clean and dry skin before creams, oils or moisturizers. Spread evenly across the face and neck with your fingertips. Gently pat it on for enhanced absorption.",
  },
  {
    id: 5,
    MRP: "M.R.P.:	₹650.00",
    Taxes: "Inclusive of all taxes",
    yousave: "You Save:",
    Delivery: "FREE Delivery over ₹499. Fulfilled by Amazon.",
    About: "About This Item",
    ItemTwo:
      "It is ideal for a quick snack, as part of a healthy salad, in kids’ tiffin-boxes or a complete meal for the family",
    Item: "Made using fine quality durum wheat semolina",
    save: "₹851.00 (53%)",
    Image: "./Images/BeautyFive.webp",
    Deal: "DEAL OF THE DAY",
    price: "	₹7499.00 (₹749.00 / l)",
    Delivery: "FREE Delivery over ₹499. Fulfilled by Amazon.",
    Price: "₹491.00 (₹1,636.67 /100 ml)",
    Free: "FREE delivery Sunday, 13 November on first order. ",
    Location: "Select you Location",
    sold: "Sold by Pilgrim India and Fulfilled by Amazon.",
    Deal: "DEAL OF THE DAY:",
    text: "Barilla Ricotta Pasta and Pizza Sauce, 400g | Non - GMO Project Ver| Gluten free | No added Colour or Presevatives ",
    ItemThree:
      "AHA BHA PEELING SOLUTION EXFOLIATES DEAD SKIN CELLS - Lactic Acid brightens and refines skin texture. Reduces acne and alleviates dullness. Treat yourself to the luxury of an at-home facial with the Pilgrim 25% AHA, 2% BHA, 5% PHA Peeling Solution.",
    ItemFour:
      "NATURAL INGREDIENTS, NO TOXINS - Crafted following strict guidelines of THE PILGRIM CODE, the Peeling Solution is FDA approved, Contains No Paraben, No Sulphates, No Mineral Oils as well as other harsh chemicals and is cruelty-free.",
    ItemFive:
      "Increases skin hydration to reduce the look of fine lines & wrinkles. Gently exfoliates to reveal bright and youthful skin.",
    DetailKey: "Product Dimensions :",
    DetailValue: "19 x 11 x 9.5 cm; 30 Grams",
    DetailKeyOne: "Date First Available:",
    DetailValueOne: "27 December 2019",
    DetailKeyTwo: "Manufacturer :",
    DetailValueTwo: "For Pilgrim India (Aelius Parallel Holdings Pvt Ltd.)",
    DetailKeyThree: "ASIN  : ",
    DetailValueThree: "B0836Y7S2C",
    DetailKeyFour: "Item model number  : ",
    DetailValueFour: "PGKNS1",
    DetailKeyFive: "Country of Origin  : ",
    DetailValueFive: " India",
    DetailKeySix: "Manufacturer  : ",
    DetailValueSix: "For Pilgrim India (Aelius Parallel Holdings Pvt Ltd.)",
    DetailKeySeven: "Item Weight  : ",
    DetailValueSeven: "90 g",
    DetailKeyEight: "Net Quantity  :",
    DetailValueEight: "30 millilitre",
    DetailKeyNine: "Best Sellers Rank: ",
    DetailValueNine: "#1,618 in Beauty",
    Detail: "Product Detail",
    save_extra: "Save Extra",
    save_extraTwo: "with 2 offers",
    Partner_Offer: "Partner Offers (2):",
    Partner_Offer_Two:
      "Buy more and save up to 10% extra. Offered by Pilgrim India",
    Bank_Offer: "Bank Offer (2): ",
    Bank_Offer_Two:
      "10% Instant Discount up to INR 500 on OneCard Credit Card Trxn. Min purchase value INR 2500 ",
    Important: "Important information",
    Safety: "Safety Information",
    SafetyHead:
      "Use twice a day, morning & night. Apply under a high SPF sunscreen during the day.",
    Indication: "Indications:",
    IndicationHead:
      "Apply 3-5 drops of serum to clean and dry skin before creams, oils or moisturizers. Spread evenly across the face and neck with your fingertips. Gently pat it on for enhanced absorption.",
  },
  {
    id: 6,
    MRP: "M.R.P.:	₹650.00",
    Taxes: "Inclusive of all taxes",
    yousave: "You Save:",
    Delivery: "FREE Delivery over ₹499. Fulfilled by Amazon.",
    About: "About This Item",
    ItemTwo:
      "ABOUT THIS PRODUCT- Himalayan Natives' 100% Natural Original Cow Ghee is packed with the nutrition that your body needs. Our Cow Ghee﻿﻿﻿ is highly nutritious and contains a rich and authentic flavor and natural aroma. It is a 100% natural and pure cow ghee that is made from the milk of free-range cows that graze exclusively on mineral-rich grass, herbs, and medicinal plants. It has no preservatives or artificial colors.",
    Item: "GREAT SOURCE OF ESSENTIAL NUTRIENTS: Himalayan Natives Natural Cow Ghee is a rich source of essential nutrients. It contains antioxidants, vitamin A, B2, B3, K2, Omega 3, and 9 fatty acids. It is one of the strongest natural antioxidants and helps in taking care of the body's overall health making it a great alternative to refined oils",
    save: "₹851.00 (53%)",
    Image: "./Images/BeautySix.webp",
    Deal: "DEAL OF THE DAY",
    price: "	₹1000.00 (₹749.00 / l)",
    text: "Himalayan Natives 100 Natural Cow Ghee 1L in  Desi ghee | Cow ghee of Original | Pure Cow gh | Pure Cow Ghee in for Bt. Immunity and Aid Hearth Health |",
    Delivery: "FREE Delivery over ₹499. Fulfilled by Amazon.",
    Price: "₹491.00 (₹1,636.67 /100 ml)",
    Free: "FREE delivery Sunday, 13 November on first order. ",
    Location: "Select you Location",
    sold: "Sold by Pilgrim India and Fulfilled by Amazon.",
    Deal: "DEAL OF THE DAY:",
    ItemThree:
      "AHA BHA PEELING SOLUTION EXFOLIATES DEAD SKIN CELLS - Lactic Acid brightens and refines skin texture. Reduces acne and alleviates dullness. Treat yourself to the luxury of an at-home facial with the Pilgrim 25% AHA, 2% BHA, 5% PHA Peeling Solution.",
    ItemFour:
      "NATURAL INGREDIENTS, NO TOXINS - Crafted following strict guidelines of THE PILGRIM CODE, the Peeling Solution is FDA approved, Contains No Paraben, No Sulphates, No Mineral Oils as well as other harsh chemicals and is cruelty-free.",
    ItemFive:
      "Increases skin hydration to reduce the look of fine lines & wrinkles. Gently exfoliates to reveal bright and youthful skin.",
    DetailKey: "Product Dimensions :",
    DetailValue: "19 x 11 x 9.5 cm; 30 Grams",
    DetailKeyOne: "Date First Available:",
    DetailValueOne: "27 December 2019",
    DetailKeyTwo: "Manufacturer :",
    DetailValueTwo: "For Pilgrim India (Aelius Parallel Holdings Pvt Ltd.)",
    DetailKeyThree: "ASIN  : ",
    DetailValueThree: "B0836Y7S2C",
    DetailKeyFour: "Item model number  : ",
    DetailValueFour: "PGKNS1",
    DetailKeyFive: "Country of Origin  : ",
    DetailValueFive: " India",
    DetailKeySix: "Manufacturer  : ",
    DetailValueSix: "For Pilgrim India (Aelius Parallel Holdings Pvt Ltd.)",
    DetailKeySeven: "Item Weight  : ",
    DetailValueSeven: "90 g",
    DetailKeyEight: "Net Quantity  :",
    DetailValueEight: "30 millilitre",
    DetailKeyNine: "Best Sellers Rank: ",
    DetailValueNine: "#1,618 in Beauty",
    Detail: "Product Detail",
    save_extra: "Save Extra",
    save_extraTwo: "with 2 offers",
    Partner_Offer: "Partner Offers (2):",
    Partner_Offer_Two:
      "Buy more and save up to 10% extra. Offered by Pilgrim India",
    Bank_Offer: "Bank Offer (2): ",
    Bank_Offer_Two:
      "10% Instant Discount up to INR 500 on OneCard Credit Card Trxn. Min purchase value INR 2500 ",
    Important: "Important information",
    Safety: "Safety Information",
    SafetyHead:
      "Use twice a day, morning & night. Apply under a high SPF sunscreen during the day.",
    Indication: "Indications:",
    IndicationHead:
      "Apply 3-5 drops of serum to clean and dry skin before creams, oils or moisturizers. Spread evenly across the face and neck with your fingertips. Gently pat it on for enhanced absorption.",
  },
];

// Sports
export const Fitness = [
  {
    image: "./Images/FitnessOne.jpg",
  },
  {
    image: "./Images/FitnessTwo.jpg",
  },
  {
    image: "./Images/FitnessThree.jpg",
  },
  {
    image: "./Images/FitnessFour.jpg",
  },
  {
    image: "./Images/FitnessFive.jpg",
  },
];

// Products

export const product = [
  {
    Text: "Now India Will Say Bought On Amazon amazone",
    img: "./Images/123.jpg",
    link: "Se All Incoming offer",
  },

  {
    Text: "Grab the best deals before sales on amazone",
    img: "./Images/h1.jpg",
    link: "Se All Incoming offer",
  },
  {
    Text: "Sell on Amazone with 70% off on selling free",
    img: "./Images/h2.jpg",
    link: "Se All Incoming offer",
  },
  {
    Text: "Grab the best deals before sales on amazone",
    img: "./Images/h3.jpg",
    link: "Se All Incoming offer",
  },
];
